---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-hosting
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "git@github.com:blade2005/homelab.git"
    path: kubernetes/apps/selfhosted/immich
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: image-hosting
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
