---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
# https://github.com/jameswynn/helm-charts/tree/main/charts/image-hosting
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-hosting-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    chart: immich
    targetRevision: 0.7.0
    helm:
      valuesObject:
        immich:
          metrics:
            enabled: true
          persistence:
            library:
              existingClaim: "immich-library-pvc"
        postgresql:
          global:
            postgresql:
              auth:
                existingSecret: "postgres-credentials"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "image-hosting"
