---
ci:
  autofix_prs: true
  autoupdate_branch: bugfix/pre-commit-fixes
minimum_pre_commit_version: 2.13.0
repos:
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
  - hooks:
      - id: no-commit-to-branch
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe # required for cfn or yaml with custom import (!)
      - id: trailing-whitespace
      - id: check-symlinks
      - id: check-builtin-literals
      - id: check-ast
      - id: check-added-large-files
      - id: debug-statements
      - id: mixed-line-ending
      - id: requirements-txt-fixer
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
  - hooks:
      - id: check-github-workflows
      - id: check-github-actions
      - id: check-dependabot
      - id: check-taskfile
      - id: check-renovate
    repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.0
  - hooks:
      - additional_dependencies:
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-toc
          - mdformat-config
        id: mdformat
    repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.10.1
    hooks:
      - id: cspell
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
  - hooks:
      - id: yamlfmt
    repo: https://github.com/google/yamlfmt
    rev: v0.13.0
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.1.0" # Use the sha / tag you want to point at
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.4.1"]
