---
version: "3"
vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
includes:
  ansible:
    taskfile: .taskfiles/ansible/Taskfile.yaml
    dir: ansible
tasks:
  default:
    desc: "List tasks"
    silent: true
    cmds:
      - task -l
  check:
    desc: "Check Project"
    silent: true
    cmds:
      - pre-commit run -a
      - task: ansible:check
