---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-tunnel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: "https://cloudflare.github.io/helm-charts"
    targetRevision: 0.3.0
    chart: cloudflare-tunnel
    helm:
      valuesObject:
        image:
          tag: 2024.6.1
        cloudflare:
          secretName: "rook-ceph-tunnel-credentials"
          tunnelName: "faerun-rook-ceph"
          ingress:
            - hostname: "rook.fieldsofbears.com"
              service: "http://rook-ceph-mgr-dashboard.rook-ceph.svc.cluster.local:7000"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    automated: {}
