---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.14.7
    valuesInline:
      prometheus:
        scrapeAnnotations: true
        serviceAccount: "monitoring-prometheus-kube-prometheus"
        namespace: monitoring
        podMonitor:
          enabled: false
        serviceMonitor:
          enabled: false
        prometheusRule:
          enabled: true
resources:
  - ippool.yaml
  - l2config.yaml
