---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.9.20
    valuesInline:
      deploymentAnnotations:
        argocd.argoproj.io/sync-wave: "3"
      podAnnotations:
        argocd.argoproj.io/sync-wave: "3"
      installCRDs: true
      serviceMonitor:
        enabled: true
        interval: 1m
      webhook:
        serviceMonitor:
          enabled: true
          interval: 1m
      certController:
        serviceMonitor:
          enabled: true
          interval: 1m
resources:
  - ./onepassword-cluster-secret-store.yaml
