---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage-tunnel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://cloudflare.github.io/helm-charts"
    targetRevision: 0.3.0
    chart: cloudflare-tunnel
    helm:
      valuesObject:
        image:
          tag: 2024.6.1
        cloudflare:
          secretName: "homepage-tunnel-credentials"
          tunnelName: "faerun-homepage"
          ingress:
            - hostname: "fieldsofbears.com"
              service: "http://homepage-app.homelab.svc.cluster.local:3000"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homelab
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
