---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/requirements.json
roles:
  - name: artis3n.tailscale
  - name: xolyu.mariadb
  - name: adrianjuhl.rbenv
collections:
  - name: community.general
  - name: https://github.com/stoneydavis/ansible-collection-pterodactyl.git
    type: git
  - name: community.docker
