apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader-svc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    targetRevision: 1.0.115
  destination:
    server: "https://kubernetes.default.svc"
    namespace: reloader
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
