---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unpackerr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    namespace: homelab
    purpose: media-unpacking
spec:
  project: default
  source:
    repoURL: "git@github.com:blade2005/homelab.git"
    path: kubernetes/apps/homelab/unpackerr
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homelab
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
