---
name: 'Check spelling'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
